package DesginDoAn;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

public class FrameDatPhong extends JFrame {

    public JButton b1, b2, b3, b4, b5, b6, b7, b8;
    public JLabel l1, l2, l3, l4, l5, l6, l7, l8, l9, SLSingle, SLFamily, SLCouple, SLVIP, total;
    String DichVu[] = {"Tron Goi", "Di Chuyen", "An Uong", "Khong"};
    JComboBox cb = new JComboBox(DichVu);
    JComboBox cb1 = new JComboBox(DichVu);
    JComboBox cb2 = new JComboBox(DichVu);
    JComboBox cb3 = new JComboBox(DichVu);
    JLabel Single = new JLabel("Single");
    JLabel Family = new JLabel("Family");
    JLabel Couple = new JLabel("Couple");
    JLabel VIP = new JLabel("V.I.P");
    public JTextField from1, to1;
    JRadioButton r1, r2;
    ButtonGroup bg = new ButtonGroup();

    FrameDatPhong() {
        DisPlay();
    }

    private void DisPlay() {
        setTitle("Dat Phong");
        setVisible(true);
        //f3.setResizable(false);
        setBounds(270, 20, 700, 600);
        setLayout(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // tao 1 panel add 25 panel vao 1 panel
        JPanel pt = new JPanel(new GridLayout(6, 5));
        pt.setBounds(100, 100, 500, 400);
        // ten danh nghiep
        JLabel title = new JLabel("Khach San Lau");
        title.setFont(new Font(null, Font.CENTER_BASELINE, 20));
        title.setBounds(300, 10, 200, 30);
        JLabel dayNow = new JLabel("Ngay: " + java.time.LocalDate.now().toString());
        dayNow.setBounds(320, 35, 100, 20);
        // tao 2 label va 2 text de nhap ngay vao.
        JLabel from = new JLabel("From");
        JLabel to = new JLabel("to");
        from.setBounds(250, 60, 40, 20);
        from1 = new JTextField("dd/MM/YYYY");
        from1.setBounds(290, 60, 100, 20);
        to.setBounds(390, 60, 20, 20);
        to1 = new JTextField("dd/MM/YYYY");
        to1.setBounds(410, 60, 100, 20);
        JPanel p1 = new JPanel();
        p1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p2 = new JPanel();
        p2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p3 = new JPanel();
        p3.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p4 = new JPanel();
        p4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p5 = new JPanel();
        p5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p6 = new JPanel();
        p6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p7 = new JPanel();
        p7.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p8 = new JPanel();
        p8.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p9 = new JPanel();
        p9.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p10 = new JPanel(null);
        p10.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p11 = new JPanel();
        p11.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p12 = new JPanel();
        p12.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p13 = new JPanel();
        p13.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p14 = new JPanel();
        p14.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p15 = new JPanel(null);
        p15.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p16 = new JPanel();
        p16.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p17 = new JPanel();
        p17.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p18 = new JPanel();
        p18.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p19 = new JPanel();
        p19.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p20 = new JPanel(null);
        p20.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p21 = new JPanel();
        p21.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p22 = new JPanel();
        p22.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p23 = new JPanel();
        p23.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p24 = new JPanel();
        p24.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel p25 = new JPanel(null);
        p25.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        l1 = new JLabel("Loai Phong");
        l2 = new JLabel("So Nguoi");
        l3 = new JLabel("Dich Vu");
        l4 = new JLabel("Gia");
        l5 = new JLabel("So Luong");
        l6 = new JLabel("Phong Don");
        l7 = new JLabel("Phong Doi");
        l8 = new JLabel("Phong Gia Dinh");
        l9 = new JLabel("Phong V.I.P");
        // create label add in panel
        p1.add(l1);
        p2.add(l2);
        p3.add(l3);
        p4.add(l4);
        p5.add(l5);
        p6.add(l6);
        p11.add(l7);
        p16.add(l8);
        p21.add(l9);
        p8.add(cb);
        p13.add(cb1);
        p18.add(cb2);
        p23.add(cb3);
        p9.add(Single);
        p14.add(Couple);
        p19.add(Family);
        p24.add(VIP);
        b1 = new JButton("-");
        b1.setBounds(5, 30, 45, 30);
        SLSingle = new JLabel("0", JLabel.CENTER);
        SLSingle.setBounds(43, 10, 10, 10);
        b2 = new JButton("+");
        b2.setBounds(50, 30, 45, 30);
        p10.add(SLSingle);
        p10.add(b2);
        p10.add(b1);
        b3 = new JButton("+");
        b3.setBounds(50, 30, 45, 30);
        SLCouple = new JLabel("0");
        SLCouple.setBounds(43, 10, 10, 10);
        b4 = new JButton("-");
        b4.setBounds(5, 30, 45, 30);
        p15.add(SLCouple);
        p15.add(b4);
        p15.add(b3);
        b5 = new JButton("+");
        b5.setBounds(50, 30, 45, 30);
        SLFamily = new JLabel("0");
        SLFamily.setBounds(43, 10, 10, 10);
        b6 = new JButton("-");
        b6.setBounds(5, 30, 45, 30);
        p20.add(SLFamily);
        p20.add(b6);
        p20.add(b5);
        b7 = new JButton("+");
        b7.setBounds(50, 30, 45, 30);
        SLVIP = new JLabel("0");
        SLVIP.setBounds(43, 10, 10, 10);
        b8 = new JButton("-");
        b8.setBounds(5, 30, 45, 30);
        p25.add(SLVIP);
        p25.add(b8);
        p25.add(b7);
        r1 = new JRadioButton("Tien Mat");
        r1.setBounds(120, 400, 100, 30);
        r2 = new JRadioButton("Master Card");
        JPanel tt = new JPanel();
        tt.setBorder(BorderFactory.createTitledBorder("Hinh Thuc Thanh Toan"));
        tt.setBounds(400, 435, 200, 50);
        bg.add(r1);
        bg.add(r2);
        total = new JLabel("Tong Tien: ");
        total.setBounds(100, 440, 250, 30);
        JButton DP = new JButton("DAT NGAY");
        DP.setBounds(100, 500, 500, 40);
        DP.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                new FormCustomer();
            }
            
        });
        add(DP);
        add(title);
        add(dayNow);
        add(from);
        add(from1);
        add(to);
        add(to1);
        add(total);
        add(tt);
        add(pt);
        tt.add(r1);
        tt.add(r2);
        pt.add(p1);
        pt.add(p2);
        pt.add(p3);
        pt.add(p4);
        pt.add(p5);
        pt.add(p6);
        pt.add(p7);
        pt.add(p8);
        pt.add(p9);
        pt.add(p10);
        pt.add(p11);
        pt.add(p12);
        pt.add(p13);
        pt.add(p14);
        pt.add(p15);
        pt.add(p16);
        pt.add(p17);
        pt.add(p18);
        pt.add(p19);
        pt.add(p20);
        pt.add(p21);
        pt.add(p22);
        pt.add(p23);
        pt.add(p24);
        pt.add(p25);
    }
}
